### ISSUE TITLE
allow topic format to add more segments

### ISSUE THREAD

**Issue by cmnstmntmn** [hikhvar/mqtt2prometheus#1]
hey @hikhvar,

first of all, great work! this tool is the missing piece of the golden puzzle.

i have a question regarding the topic format

```yaml
# The Topic path to subscripe to. Actually this will become `$topic_path/+`
topic_path: v1/devices/me
```

does it make sense to you to allow multiple levels

the way it is now

```yaml
# The Topic path to subscripe to. Actually this will become `$topic_path/#`
topic_path: v1/devices/me/
```

i'm asking this in the scenario where there is a location nesting like

```
myhome/groundflood/livingroom
myhome/groundfloor/kitchen
myhome/attic/kitchen
myhome/attic/bathroom
```

hmm

**Comment by cmnstmntmn** [comment]
i belive this is a bit impossible since there is no way to determne the label key, based on the topic

```
temperature{?="groundfloor", ?="livingroom"} 43.0
temperature{?="attic", ?="kitchen} 43.0
```

**Comment by cmnstmntmn** [comment]
as a solution i could go for

```yaml
topic_path: myhome/+
```

and extract the data using regex over

```
received_messages{status="success",topic="myhome/attic/kitchen/temperature"} 1.0
```

still i guess is overkill

**Comment by hikhvar** [comment]
The current implementation does not allow that. Moreover, I assume that there are multiple metrics in a message on a topic. 

I will have a look into it, if we can implement some labeling based on the topic path.

**Comment by hikhvar** [comment]
It has been a long time, but I appended in #14 the MQTT topic as label to every metric. And the new `device_id_regex` configuration options allows an arbitrary position of the device ID in the topic path. 

Since we have the source topic attached to the metrics, we can use prometheus relabeling to dissect the topic into the labels you want.

**Comment by cmnstmntmn** [comment]
@hikhvar this sounds great!
