### ISSUE TITLE
Metrics not matching `sensor_name_filter` treated as errors

### ISSUE THREAD

**Issue by wmoss** [hikhvar/mqtt2prometheus#112]
Perhaps this is feature and not a bug, so please help me understand if I misunderstanding.

I'm trying to use `sensor_name_filter` to filter out sensors (e.g. mqtt topics) that produce a specific mqtt metric (e.g key in the json value published on the topic). It works (e.g. doesn't parse and generate metrics for topics that don't match), however, it treats it as an error state, producing and error metric for Prometheus and also logging the error. 

From reading the code, it seems to me like the problem is that the check for `SensorNameFilter.Match` should not happen in `parse.validMetric`, since not finding the config is a error case (albeit a pathological one, since  it just checked to see that there was something in the config in the extractor configured in `NewJSONObjectExtractor`) but it not matching the filter is not. `parseMetric` is currently required to return something so there's not really way to filter from in there at all, so a bit of a code refactor would be required to make this work.

I'm happy to put together a pull request if you agree the behavior I'm describing is, in fact, correct.

**Comment by hikhvar** [comment]
Yeah, you are right. We should refactor the code a bit to have an extra filtering stage in the "parse-extract-store" logic for each received MQTT event.

I will happily review the pull request changing that.

**Comment by wmoss** [comment]
Sounds good, I'll try to put something up to fix this.

**Comment by hikhvar** [comment]
Should be fixed by #115 ?

**Comment by wmoss** [comment]
Yup!
