### ISSUE TITLE
Running 2 instances on the same host causes connection resets on mqtt

### ISSUE THREAD

**Issue by scouratier** [hikhvar/mqtt2prometheus#119]
Situation:
- I run 2 different docker containers
Container 1 uses config1 and runs on port 9641
Container 2 uses config2 and runs on port 9642
Both containers connect to the same mqtt broker.

These are the logs I get from the mqtt broker:

> 1675339210: New connection from 192.168.1.2:55500 on port 1883.
> 1675339210: Client stablecottage-1 already connected, closing old connection.
> 1675339210: New client connected from 192.168.1.2:55500 as stablecottage-1 (p2, c1, k30).
> 1675339210: New connection from 192.168.1.2:55508 on port 1883.
> 1675339210: Client stablecottage-1 already connected, closing old connection.
> 1675339210: New client connected from 192.168.1.2:55508 as stablecottage-1 (p2, c1, k30).
> 1675339210: New connection from 192.168.1.2:55512 on port 1883.
> 1675339210: Client stablecottage-1 already connected, closing old connection.
> 1675339210: New client connected from 192.168.1.2:55512 as stablecottage-1 (p2, c1, k30).
> 1675339210: New connection from 192.168.1.2:55522 on port 1883.
> 1675339210: Client stablecottage-1 already connected, closing old connection.
> 1675339210: New client connected from 192.168.1.2:55522 as stablecottage-1 (p2, c1, k30).
> 1675339210: New connection from 192.168.1.2:55524 on port 1883.
> 1675339210: Client stablecottage-1 already connected, closing old connection.

The end result is that both containers end up using a large amount of CPU and eventually stop working / lock up the entire host.

Request: Could the client name be randomized or better yet, could the client name be set by config or command line?

**Comment by scouratier** [comment]
Note: I've found a workout with Docker and just using -h="ANOTHERHOSTNAME"

**Comment by hikhvar** [comment]
Our you can use this parameter from the configuration file for this:
```
 client_id: somedevice
```
This is explizitly build for that usecase.

**Comment by scouratier** [comment]
Sweet. That would work as well. May I suggest you add a quick blurb on the section on running multiple clients at the same time? Or maybe I can do a PR on the readme

**Comment by hikhvar** [comment]
PR is highly welcome.
