### ISSUE TITLE
What if my network connection is not good

### ISSUE THREAD

**Issue by galleon** [hikhvar/mqtt2prometheus#126]
Hello,

Thanks for this work. I have a small question before exploring further with MQTT2prometheus.

I have a bunch of sensors publishing to an MQTT server. It happen that the connection between this MQTT server and my prometheus server can be flaky. That's is not much of a problem because the data is saved in MQTT using timestamped messages.

Is it possible when my connection is back to ingest all messages using MQTT2prometheus - including messages in the "past" ?

Thanks

**Comment by hikhvar** [comment]
Hey, currently not. The exporter only stores the last seen value. The prometheus scraping API wouldn't allow us to present multiple points in time for the same metric AFAIK. That would require the exporter to implement the prometheus remote-write feature. A work-around for that could be:
Deploy a small prometheus server in agent mode alongside the prometheus server. Than use remote-write of the agent mode server, to push into your central prometheus instances.

See this blog post for details on the agent mode: https://prometheus.io/blog/2021/11/16/agent/
