### ISSUE TITLE
Document how to configure Prometheus

### ISSUE THREAD

**Issue by voltagex** [hikhvar/mqtt2prometheus#15]
I just installed and set up mqtt2prometheus, but there's no info on what needs to be changed in Prometheus to make it grab data. Would it be possible to provide an example? I'm guessing I have to make Prometheus connect to your daemon on port 8002 somehow.

**Comment by voltagex** [comment]
```
  - job_name: 'energy'
    static_configs:
      - targets: ['localhost:8002']
```

appears to work

**Comment by hikhvar** [comment]
Hey, 
there is a complete local development environment based on docker-compose in https://github.com/hikhvar/mqtt2prometheus/tree/master/hack

This is the scrape configuration: https://github.com/hikhvar/mqtt2prometheus/blob/master/hack/prometheus.yml#L22-L30

**Comment by voltagex** [comment]
Hey sorry for missing that one and thanks for the pointer.

**Comment by hikhvar** [comment]
No problem, added a link in the Readme to help others.
