### ISSUE TITLE
Incorrect port used 

### ISSUE THREAD

**Issue by vikramsubramanian** [hikhvar/mqtt2prometheus#17]
mqtt2prometheus is built from source in hack/docker-compose.yml. Shouldn't the port then be 9641:9641 instead of 8002:8002 for the mqtt2prometheus service? 

I'd be happy to submit a pull request for the issue.

Thanks,
Vikram

**Comment by hikhvar** [comment]
Yes, I missed the hacking directory after assigning the new port. 8002 ist also configured in the prometheus configuration. I welcome a PR.

**Comment by hikhvar** [comment]
Closing this, since the PR is merged.
