### ISSUE TITLE
Migrate to GitHub Container Registry for Docker images

### ISSUE THREAD

**Issue by nightvisi0n** [hikhvar/mqtt2prometheus#22]
Currently it is not possible to pull the `mqtt2prometheus` docker image without authentication.  
GitHub [made this possible](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry#visibility-and-access-permissions-for-container-images) in their new `GitHub Container Registry`.  

Therefore I propose to migrate to the new platform: https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images

**Comment by hikhvar** [comment]
As discussed in #20 the current docker image publishing mode is not perfect. I will try to resolve this.

**Comment by hikhvar** [comment]
I push now to ghcr.io/hikhvar/mqtt2prometheus. However I'm currently not able to pull from that registry :thinking:
