### ISSUE TITLE
Wrong port - Keep port usage consistent

### ISSUE THREAD

**Issue by CalvinSchwartz** [hikhvar/mqtt2prometheus#35]
Hi,
I build the docker image on a RPI 4 and tried to run it with -p 8002:8002 which didn't work.
It must be -p 8002:9641 which isn't mentioned in the Readme.md.

I suggest to either change the port during building to 8002 or keep it as it is at 9641 and mention this in the Readme.md

Additionally it would be nice if ARM images are provided on Dockerhub.

**Comment by hikhvar** [comment]
I fixed the outdated port 8002. 
I'm currently waiting for ARM support in goreleaser. https://github.com/goreleaser/goreleaser/issues/530
The progress looked promising the last time I had a look into that project. But this effort seems to lost the traction, hence I have to have a look into alternatives.
