### ISSUE TITLE
Publish multi-arch Docker images supporting ARM

### ISSUE THREAD

**Issue by hikhvar** [hikhvar/mqtt2prometheus#36]
Currently only x86-64 compatible docker images are pushed into the public registries. Since MQTT is often used in embedded contexts, or home automation setups with a raspberry PI as main hub, ARM docker images should be published.

Option a) Wait For /Push this efffort in goreleaser: goreleaser. https://github.com/goreleaser/goreleaser/issues/530
Option b) Build the docker images with another tool.

**Comment by CalvinSchwartz** [comment]
Option b)
One example would be: [deploy.yml](https://github.com/mikenye/docker-flightradar24/blob/master/.github/workflows/deploy.yml) where I guess it could be directly copied to run it with minor changes.
Additionally see: https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

I'll maybe try this later this week to check if it works.

**Comment by hikhvar** [comment]
I had a look into a). They seem to support multiarch already: https://goreleaser.com/customization/docker_manifest/

I like to use goreleaser for building the images since go releaser also generates the changelogs with the links to the docker images.
