### ISSUE TITLE
Publish to a publicly available image registry

### ISSUE THREAD

**Issue by michael-robbins** [hikhvar/mqtt2prometheus#40]
Hey! Just trying this out and noticed you've only published to Github's container registry, what are the chances of also publishing to Docker Hub or similar registry that doesn't require authentication before pulling?

It's really hard to automate the deployment of this image when I need to pass my github creds everywhere across my network!

Thanks!!

**Comment by michael-robbins** [comment]
Ahh poking around the Github action I can see you're pushing there actually! https://hub.docker.com/r/hikhvar/mqtt2prometheus

Might be worth updating the README to include links to that too!

**Comment by hikhvar** [comment]
Thanks for the pointer. Missed to update those images. However I advise you to use the images linked on the [Releases Page](https://github.com/hikhvar/mqtt2prometheus/releases). Those images are linked to a proper version. The latest version reflects the master and may break at any point in time.
