### ISSUE TITLE
Cannot connect to a TLS enabled MQTT broker? CA certs missing in container?

### ISSUE THREAD

**Issue by michael-robbins** [hikhvar/mqtt2prometheus#41]
Heya, just trying out this tool and struggling to get connected to my MQTT broker (eclipse-mosquitto) with TLS enabled (and working with a few different programs already, paho.mqtt.python library to name a good example).

I'm got the below setup:
```
mqtt:
  server: ssl://mqtt.my.proper.domain.name:8883
```

```
michael@server:~$ openssl s_client -connect mqtt.my.proper.domain.name:8883
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = mqtt.my.proper.domain.name
verify return:1
---
Certificate chain
 0 s:CN = mqtt.my.proper.domain.name
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
```

And I'm seeing this error repeating:
```
2021-02-28T12:19:49Z	warn	cmd/mqtt2prometheus.go:99	could not connect to mqtt broker %s, sleep 10 second	{"error": "Network Error : x509: certificate signed by unknown authority"}
```

Now I know the certificate is signed by letsencrypt and that's all dandy, so I'm going to go out on a limb and say the CA certs in the image are either missing/out of date/etc? Not 100% sure?

I'm poking around on the internet to see if there's other Go libraries that have similar issues!

**Comment by michael-robbins** [comment]
My guess is it's related to the use of `FROM scratch` and the lack of CA certs in there!

https://medium.com/on-docker/use-multi-stage-builds-to-inject-ca-certs-ad1e8f01de1b

What are the chances of modifying the Dockerfile to take a similar approach to this link and bring in the CA certs from alpine?

**Comment by hikhvar** [comment]
I think I will switch the base image to gcr.io/distroless/static-debian10

**Comment by michael-robbins** [comment]
Nice! Thanks! I'll keep an eye out for the next release and come back and try again then! Cheers for the quick response!

**Comment by hikhvar** [comment]
I just issued a new pre release v0.1.6-RC2. As soon as the actions are finished you find the newly build image on dockerhub and the github container registry.
