### ISSUE TITLE
deviceid regex idea expanded on

### ISSUE THREAD

**Issue by michael-robbins** [hikhvar/mqtt2prometheus#45]
Hiya!

I really like the device_id named regex group idea, I'm wondering what's the appetite to expand that and have other named groups to extra metadata from the topic name and include them as attributes in the metric?

For example:

MQTT Message:
```
{"temperature":23.20,"humidity":51.60, "computed": {"heat_index":22.92} }
```

MQTT Topic:
```
site/melbourne/north/weather-01/metrics
```

Device ID Regex:
```
"site/(?P<site>[^\\/]+)/(?P<category>[^\\/]+)/(?P<deviceid>[^\\/]+)/metrics"
```

Would result in:
```
temperature{site="melbourne",category="north",deviceid="weather-01",topic="site/melbourne/north/weather-01/metrics"} 23.2
heat_index{site="melbourne",category="north",deviceid="weather-01",topic="site/melbourne/north/weather-01/metrics"} 22.92
humidity{site="melbourne",category="north",deviceid="weather-01",topic="site/melbourne/north/weather-01/metrics"} 51.6
```

I'm not actually sure what the deviceid regex actually does, as your example in the README doesn't actually include the 'output' of the named group in any examples? Or maybe deviceid is a prometheus concept I haven't discovered yet!

But what are your thoughts about the above?

**Comment by hikhvar** [comment]
The device ID is a concept of this exporter. Every metric is a sensor value reported via MQTT. The metrics (temperature, humidity) etc have a different value for each sensor, hence we need the device ID to seperate the values of those metrics into different time series. The value of the device ID will be the value of the "sensor" prometheus label. 

We can expand the device ID regex, however there is already such a relabel capability inside prometheus. Since we export the topic path as prometheus label, you can use [prometheus relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) to implement your usecase.

**Comment by michael-robbins** [comment]
Ahh ok, interesting!

So in your example in the README

```
{"temperature":23.20,"humidity":51.60, "computed": {"heat_index":22.92} }
```

Sent to topic `devices/me/livingroom`

Results in:
```
temperature{sensor="livingroom",topic="devices/me/livingroom"} 23.2
heat_index{sensor="livingroom",topic="devices/me/livingroom"} 22.92
humidity{sensor="livingroom",topic="devices/me/livingroom"} 51.6
```

What would be the 'device_id_regex'? Would the 'deviceid' in this case be `livingroom` assuming the default device_id_regex of: `"(.*/)?(?P<deviceid>.*)"`

Which I'm guessing means 'take the last level of the topic and use that? But is that then renamed to 'sensor'? Or if not, how does it know that `sensor="livingroom"`

I think that's the main source of my confusion here! Apart from this all the other docs seem to be easy enough to read/parse :D

**Comment by hikhvar** [comment]
The `device_id_regex` is a rather new concept. The exporter assumed a long time that the last part of the topic path was the device ID. So all in all, I thing have to refactor the complete Readme.

**Comment by michael-robbins** [comment]
Ahh ok sorry I must have missed that, so previously the last part was always the 'device id' which is labelled 'sensor' when its provided to prometheus! Yeah in my mind I was looking for the 'device id' label or something, but instead it's 'sensor'!

So in my original post, if the message/topic/regex were all like they are, the resulting prometheus metrics would be this?
```
temperature{sensor="weather-01",topic="site/melbourne/north/weather-01/metrics"} 23.2
heat_index{sensor="weather-01",topic="site/melbourne/north/weather-01/metrics"} 22.92
humidity{sensor="weather-01",topic="site/melbourne/north/weather-01/metrics"} 51.6
```

**Comment by hikhvar** [comment]
Yes, that will be the resulting prometheus metrics. If you want to fetch other labels from that topic you can use relabeling in prometheus job configuration.

**Comment by michael-robbins** [comment]
OK awesome, totally understand it now, when I get some time happy to help PR a few doco updates/etc with my (simpler) understanding :D
