### ISSUE TITLE
How to detect when MQTT is unreachable

### ISSUE THREAD

**Issue by sooslaca** [hikhvar/mqtt2prometheus#51]
Hello,

I'm might be off here a bit, but would like to get a bit of help, how would we detect by this exporter if the connection between the exported and MQTT is down?
I read the `cache` timeout option which is keeping data there for a defined amount of time.

What I would like to get help with: how would I see if mqtt2prometheus exporter is UP but my MQTT bridge is down (or connectivity between mqtt2prometheus and MQTT bridge is down)

Let's say I monitoring temperature (gauge) and losing my MQTT and cache is there forever (-1), showing "old" values forever. I would like to see somehow that my MQTT is having issues so I can fix it.

Any idea?

Thanks

**Comment by hikhvar** [comment]
Currently there is no direct metric reflecting the connection status between the broker and mqtt2prometheus. 
However, the mqtt2prometheus exports the timestamp of the last metric update. A metric update is triggered by an incoming MQTT message. Even if you set the cache to forever, old values are always exported with the last update timestamp attached.

For example this metric was updated the last time at the unix timetamp `1615575767131`. 
```
# HELP temperature DHT22 temperature reading
# TYPE temperature gauge
temperature{sensor="test",sensor_type="dht22",topic="v1/devices/me/test"} 12 1615575767131
```
The prometheus internal stale metrics semantic, will hold that value for 5 minutes (default, but configurable). The following picture shows thie data point above in prometheus. I send only one MQTT message with a temperature value.
![image](https://user-images.githubusercontent.com/263448/110987394-4e1c0600-836f-11eb-93ac-c74dd4b75a0a.png)

So if the metric disapperas (`absent(temperature)>0`) you can triggern an alert. This allows you to alert if you don't receive any metric updates. This does not tell you if the connection between the broker and mqtt2prometheus is broken or between the broker and the sensor. 

I did a quick research. The used MQTT client offers callback for [OnConnctionLost](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetConnectionLostHandler) and [OnConnected](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetOnConnectHandler). I think I will use those handlers to set a gauge to either connected or disconnected. I think that should fit your scenario?

**Comment by hikhvar** [comment]
I added this in 30a2180cfa5114a3b31ef2b7e62d951879eda7e5.
The prerelease https://github.com/hikhvar/mqtt2prometheus/releases/tag/v0.1.6-RC6 contains this gauge.

**Comment by sooslaca** [comment]
hi @hikhvar , this is awesome fix, thank you for this ! I see
```
# HELP mqtt2prometheus_connected is the mqtt2prometheus exporter connected to the broker
# TYPE mqtt2prometheus_connected gauge
mqtt2prometheus_connected 1
```
I'll just multiply this metric on the dashboard with the temperature measurement and I'll then get 0 when there is no value coming in from mqtt. (0 Celsius not important for me as I'm measuring water temperature)

**Comment by hikhvar** [comment]
I assume you use grafana for dashboarding. I use https://grafana.com/docs/grafana/latest/panels/visualizations/stat-panel/ for this usecase. Just a single number. Online or offline. The background (green/red) can be set according to the value. Hence you have a handy traffic light like signal to show your connection state.
