### ISSUE TITLE
prepelease after webconfig

### ISSUE THREAD

**Issue by sooslaca** [hikhvar/mqtt2prometheus#57]
Hi @hikhvar ,

I see it was 15 days ago when you kindly implemented webconfig (https://github.com/hikhvar/mqtt2prometheus/pull/56). Would you plan to do an RC build please?

Thank you

**Comment by hikhvar** [comment]
Hey, 
sorry missed to issue a prelease after that. I did so a couple of minutes ago.

**Comment by sooslaca** [comment]
awesomeness ! Thank you !
