### ISSUE TITLE
Exporter does not support MQTT metrics with dots in the name

### ISSUE THREAD

**Issue by protochron** [hikhvar/mqtt2prometheus#58]
The exporter doesn't support metrics in a JSON payload with dots in the key, since it uses `gojsonq`'s `Find()` method which valuates a dot as a delimiter in a JSON path. 

This means an MQTT message payload like the following will not work since the JSON parser expects a nested JSON structure:
```json
{"particles_2.5um": 5}
```
The examples don't imply that the metric names are intended to be json paths, so this seems like something that should be called out in the docs. A quick fix is to enable the ability to use a different json path delimiter in the json parser, ex.

```go
parsed := gojsonq.New(gojsonq.WithSeparator(";")).FromString(string(payload))
```
However that's not the most intuitive solution.

**Comment by hikhvar** [comment]
I think we should keep the defaults with `.` as the operator. However, adding an optional seperator, the user can specify could be really helpful. 
Sadly, I don't have that much time to work on this currently. I welcome a PR if you wan to implement this.

**Comment by hikhvar** [comment]
Thankfully @michey implemented it. Will close this issue as fixed.
