### ISSUE TITLE
Feature request: Extract custom labels from topic

### ISSUE THREAD

**Issue by tykling** [hikhvar/mqtt2prometheus#59]
Hello,

It would be nice to be able to extract labels (other than deviceid) from the mqtt topic. A new config dict with labelname: regex pairs could be very useful for adding labels with data encoded in mqtt topics.

Thanks! :)

**Comment by hikhvar** [comment]
Please have a look at this issue: https://github.com/hikhvar/mqtt2prometheus/issues/45#issuecomment-787855998

The exporter exports the topic of every metric to prometheus. You can use relabeling in prometheus to create new labels from that label: 
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

**Comment by tykling** [comment]
I am using relabelling in prom today. I can just keep doing that, although I still think it would be prettier to do it in this exporter to keep the prom config smaller. Thanks :)
