### ISSUE TITLE
MQTT listener goes 'stale'

### ISSUE THREAD

**Issue by michael-robbins** [hikhvar/mqtt2prometheus#60]
So I'm running mqtt2prometheus and it seems to generally work, but after some time, no more messages are received from mqtt.

The prometheus exporter side is still working (as prometheus reports the target as 'up').

I've enabled debug messaging, but nothing really comes up.

What kinda extra stuff can I enable? Happy to hack away and built it myself with extra debug logging enabled or something.

My guess is probably the component that listens to the mqtt topic has gone stale/timed out/needs to reconnect, but it never does and it just sits there doing nothing.

Thoughts? Might stare at the code later, just raising this as a first step :)

**Comment by michael-robbins** [comment]
Might be related to #51 but we need to go that extra step, and reconnect or something?

**Comment by hikhvar** [comment]
There might be such a bug. I use the github.com/eclipse/paho.mqtt.golang golang MQTT client. This client is based on callbacks. If this library does not call the mqtt2prometheus code, there will be no metrics update. Maybe I configured the client wrongly to automatically reconnect on failure. A second pair of eyes would be really useful.

**Comment by michael-robbins** [comment]
Yeah it's weird, here's what I've looked at so far.

I can see you're setting AutoReconnect here: https://github.com/hikhvar/mqtt2prometheus/blob/a25cf3f0b12af5cc5906ffea8d569aaa0401ded3/cmd/mqtt2prometheus.go#L84

And that looks sane to me from the package doco: https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetAutoReconnect

I know my devices writing into mqtt are online and I can connect to the broker and see the messages myself.

Querying the prometheus /metrics endpoint does tell me that it's not connected:
```
/prometheus $ wget -q -O- 'http://172.19.0.2:9641/metrics' | grep mqtt2prometheus_connected
# HELP mqtt2prometheus_connected is the mqtt2prometheus exporter connected to the broker
# TYPE mqtt2prometheus_connected gauge
mqtt2prometheus_connected 0
```

So somehow it's disconnected itself, the library has notified mqtt2prometheus correctly: https://github.com/hikhvar/mqtt2prometheus/blob/a25cf3f0b12af5cc5906ffea8d569aaa0401ded3/cmd/mqtt2prometheus.go#L109

But for some reason it's not reconnected... and then never attempts to again?

I can raise this with upstream, but then saw we've pinned to v1.1.1 which is a bit old! (https://github.com/hikhvar/mqtt2prometheus/blob/master/go.mod#L6)

Might it be worth bringing this library up to the latest version? There's a number of commits that reference reconnect handling since v1.1.1 => v1.3.4

**Comment by michael-robbins** [comment]
Might also be worth enabling dependabot if it supports go?

**Comment by michael-robbins** [comment]
Linked PR has fixed my issue *with only one day of observation so far*

Will keep an eye on it these next few days and see how we go, but looking good so far.

**Comment by hikhvar** [comment]
That sounds very promising. Sorry for the sparse response, but I'm very busy lately.

**Comment by michael-robbins** [comment]
Looks like this 'kinda' fixed the issue for a day or two, then mqtt2prometheus goes quiet again and I see nothing for days until I restart the container again.

```
2021-05-31T03:00:18+10:00	info	mqttclient/mqttClient.go:20	Connected to MQTT Broker
2021-05-31T03:00:18+10:00	info	mqttclient/mqttClient.go:21	Will subscribe to topic	{"topic": "path/to/devices/+/metrics"}
```

That was the last message on my topic, so looks like just after 2 days it went stale again....

Might just have to implement a 'restart mqtt2promethues' cron every night and see how that goes...

**Comment by michael-robbins** [comment]
I guess the issue is with the MQTT library, as we rely on that to keep the connection to the broker and ensure reconnection/etc....

**Comment by hikhvar** [comment]
I had a quick glance at the clients repositories issues. I think this is related to our issue here: https://github.com/eclipse/paho.mqtt.golang/issues/495

Currently I rebuild our new house, hence my time to work on this is very limited. Sorry 😕

**Comment by michael-robbins** [comment]
Hey please don't take it as me rushing or asking anything, just reporting my findings 🙃 

If I'm true-ly annoyed by this enough I'll dive in and debug/fix it as well, enjoy the rebuild and hope it all goes well!
