### ISSUE TITLE
I did not get the temperature and humidity value of the sensor

### ISSUE THREAD

**Issue by dudumao520** [hikhvar/mqtt2prometheus#66]
![11](https://user-images.githubusercontent.com/12032241/125895482-2a8b22e5-2660-4541-9661-0c495538e4b2.png)
The information format of my sensor is like this in the picture. How should I write it in the configuration file?
rabbitMQ+sensor, hope to get your help, thank you very much!

**Comment by dudumao520** [comment]
A003W37251330001,00-00-00-00-00,C1,026.9,N,C2,070.3,N,0D0A
------------------------------------------------------------------------------------
@hikhvar

**Comment by hikhvar** [comment]
That type of MQTT payload is currently not supported by this exporter. The payload must either be a valid JSON document or a single value. Do you have any documentation on this format? If this is a wildly known format, I welcome a Pull Request to implement that.

**Comment by dudumao520** [comment]
> That type of MQTT payload is currently not supported by this exporter. The payload must either be a valid JSON document or a single value. Do you have any documentation on this format? If this is a wildly known format, I welcome a Pull Request to implement that.

Today is the weekend, the sensor manufacturer may be off this weekend, I will ask them for some sensor documents on Monday, thank you very much for your help!

**Comment by hikhvar** [comment]
Did you get any documents from the vendor?
I would like to update this issue with the actual used format.

**Comment by hikhvar** [comment]
Close this due to no feedback.
