### ISSUE TITLE
how to config it so that I can get this item

### ISSUE THREAD

**Issue by hanjie0** [hikhvar/mqtt2prometheus#68]
Dear 
I really need this exporter for my further work. but I did not config it correctly for what I want.

Here is the data in my mqtt broker. 

{
  "app": {
    "moteeui": "32010124131300ed",
    "Class": 0,
    "type": "payload",
    "confirmed": true,
    "userdata": {
      "seqno": 1617,
      "port": 2,
      "payload": "qmcBAO0LAwBEAAAAAAAAAP4=",
      "motetx": {
        "freq": 472,
        "modu": "LORA",
        "datr": "SF7BW125",
        "codr": "4/5",
        "adr": false
      }
    },
    "gwrx": [
      {
        "eui": "34010a44124e0025",
        "time": "",
        "timefromgateway": false,
        "chan": 3,
        "rfch": 1,
        "rssi": -67,
        "lsnr": 10
      },
      {
        "eui": "34010a44124e0068",
        "time": "",
        "timefromgateway": false,
        "chan": 3,
        "rfch": 1,
        "rssi": -34,
        "lsnr": 8.8
      }
    ]
  }
}
in which, the app/userdata/payload is the mandatory item I need.  
and my topic is mdata/400101000b000c06/upALL .
the device id is 400101000b000c06
May I ask you to give an example of the configuration file to get the item as prometheus metric? 

Thank you so much !!!

**Comment by hikhvar** [comment]
`app/userdata/payload` seems to be a base64 encoded binary payload. This is not supported by this exporter, it requires either a number or a number in a string.
