### ISSUE TITLE
Suggestion for Dockerfile

### ISSUE THREAD

**Issue by snoppiz** [hikhvar/mqtt2prometheus#72]
Hello everyone,

first of all, I have to thank everybody who is working on this project.

I love to read that code, even I am pretty new in this mqtt and prometheus universe and I am struggling with this project for a while.

But I have a suggestion.
### Issue:
My first issue was to run this project as a docker container in debug-mode.
Command
`docker run -it -v "$(pwd)/config.yaml:/config.yaml"  -p  9641:9641 ghcr.io/hikhvar/mqtt2prometheus:latest -log-level debug`

But all my parameters are ignored.
I figured out that the way how the current docker image is build, it will not execute my parameters correctly.

During my try and errors, I found the issue.
Dockerfile
line 10: **CMD** ["/mqtt2prometheus"]

#### Suggestion: ###
Dockerfile
line 10: **ENTRYPOINT** ["/mqtt2prometheus"]
I read the Docker reference file as far I understand, does the start of a container use the execution as [entrypoint](https://docs.docker.com/engine/reference/builder/#entrypoint) and read all following parameters.
#### Command:
`docker run -it -v "$(pwd)/config.yaml:/config.yaml"  -p  9641:9641 ghcr.io/hikhvar/mqtt2prometheus:latest -log-level debug`

#### Result: 
The container starts with the expected log-level debug like the CLI-Version.

Thank you for your attention and maybe it helps.
Forgive me, for my terrible english.

**Comment by hikhvar** [comment]
Thank you for this very good bug report. I changed this behavior in #73. Actually I want to have the suggested behavior. 

Your english is really good. Keep on with those good bug reports!
