### ISSUE TITLE
Multiple Istance, containers

### ISSUE THREAD

**Issue by Ex4nder** [hikhvar/mqtt2prometheus#75]
Hi, I added a second istance today, I had to expose to a different localhost port (9642), and to configure another prometheus Job, is it the right way of proceding?
`<`
docker run -d -it -v "$(pwd)/config_04851E.yaml:/config.yaml"  -p  9642:9641 ghcr.io/hikhvar/mqtt2prometheus:latest
`>`
in prometheus.yml
  - job_name: '04851E'
    static_configs:
    - targets: ['localhost:9642']

**Comment by hikhvar** [comment]
I think so. Don't know enough about your local prometheus setup.
