### ISSUE TITLE
MQTT Events to Loki and Prometheus Remote-write

### ISSUE THREAD

**Issue by xkilian** [hikhvar/mqtt2prometheus#83]
Sometimes the data returned via MQTT could be events rather than a regular stream of metrics.
See the following pull request for the MQTT Sparkplug exporter which implements amongst other things:
[Pull request for IHI-Energy-Storage/sparkpluggw](https://github.com/IHI-Energy-Storage/sparkpluggw/pull/13)

- go decision tree for selecting events versus metrics (This is staticaly done in mqtt2prometheus, which is fine)
- remote-write metrics to prometheus (for added scalability with high volume event streams)
- remote-writing events to loki (in logfmt format for easy auto-parsing in loki)
- relabelling metrics natively in the exporter (for scalability concerns)
- relabelling events natively in the exporter (for scalability concerns)
- adding static labels to metrics or events (already supported by mqtt2prometheus)

You can let yourself be inspired to a more complete feature set in mqtt2prometheus.

**Comment by hikhvar** [comment]
Hello, 
currently I see mqtt2prometheus very complete in terms of feature set. I don't need inspire myself to build more into this very scoped tool. The idea is to have a simple exporter for exporting MQTT events to prometheus metrics. Thus, any integration with loki is definitely out of scope. Moreover, this is a classical prometheus exporter, thus I will not write any remote-write integrations. Scalability is not my primary target. I wrote this exporter for some home automation stuff of myself. I will welcome PR for relabeling in the exporter, but I will not spend my time to implement this feature myself.

I think, if you build any business with a high throughput of MQTT events, you businesses should be able to write such a bridge from MQTT to prometheus or loki yourself.
